name: Check links

on:
    pull_request:
        branches: [main]
    workflow_dispatch:
    schedule:
        - cron: '16 2 * * 6'

jobs:
    validate:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
        env:
            issue-lookup-label: automated-link-issue
            issue-content: ./lychee-out.md
        steps:
            - uses: actions/checkout@v4

            - name: Restore lychee cache
              uses: actions/cache@v4
              with:
                  path: .lycheecache
                  key: cache-lychee-${{ github.sha }}
                  restore-keys: cache-lychee-

            - name: Extract URLs from JSON files
              run: |
                  mkdir -p extracted-urls
                  jq -r '.url' ./conferences/2024/*.json ./conferences/2025/*.json ./conferences/2026/*.json > extracted-urls/urls.txt

            - name: Link Checker
              id: lychee
              uses: lycheeverse/lychee-action@v1.10.0
              with:
                  fail: true
                  args: --verbose --no-progress @extracted-urls/urls.txt --exclude-mail
                  output: ${{ env.issue-content }}

            # Permissions (issues: read)
            - name: 'Look for an existing issue'
              if: ${{ failure() }}
              id: last-issue
              uses: micalevisk/last-issue-action@v2
              with:
                  state: open
                  labels: ${{ env.issue-lookup-label }}

            # Permissions (issues: write)
            - name: 'Create a new issue, or update an existing one'
              if: ${{ failure() }}
              uses: peter-evans/create-issue-from-file@v4
              with:
                  title: 'docs: Broken links found'
                  content-filepath: ${{ env.issue-content }}
                  issue-number: ${{ steps['last-issue']['outputs']['issue-number'] }}
                  labels: |
                      ${{ env.issue-lookup-label }}
                      broken-link, docs
