name: Check links from PRs

on:
    pull_request:
        branches:
            - test # Cambia esto a la rama de prueba que estás usando
    workflow_dispatch: # Para poder ejecutarlo manualmente si es necesario

jobs:
    validate:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
        env:
            issue-lookup-label: automated-link-issue
            issue-content: ./lychee-out.md
        steps:
            - uses: actions/checkout@v4

            - name: Get Changed Files
              id: changed-files
              run: |
                  echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.json$')"

            - name: Extract URLs from Changed Files
              id: extract-urls
              run: |
                  mkdir -p temp
                  for file in ${{ steps.changed-files.outputs.files }}; do
                      jq -r '..|.url?|strings' $file >> temp/urls.txt
                  done
                  sort -u temp/urls.txt > temp/unique_urls.txt
                  cat temp/unique_urls.txt
              continue-on-error: true

            - name: Check for Changed Conference Files
              if: steps.changed-files.outputs.files
              run: echo "Changed conference files: ${{ steps.changed-files.outputs.files }}"

            - name: Restore lychee cache
              uses: actions/cache@v4
              with:
                  path: .lycheecache
                  key: cache-lychee-${{ github.sha }}
                  restore-keys: cache-lychee-

            - name: Link Checker
              if: steps.changed-files.outputs.files
              id: lychee
              uses: lycheeverse/lychee-action@v1.10.0
              with:
                  fail: true
                  args: --verbose --no-progress --input ./temp/unique_urls.txt --exclude-mail
                  output: ${{ env.issue-content }}

            - name: 'Look for an existing issue'
              if: ${{ failure() }}
              id: last-issue
              uses: micalevisk/last-issue-action@v2
              with:
                  state: open
                  labels: ${{ env.issue-lookup-label }}

            - name: 'Create a new issue, or update an existing one'
              if: ${{ failure() }}
              uses: peter-evans/create-issue-from-file@v4
              with:
                  title: 'docs: Broken links found'
                  content-filepath: ${{ env.issue-content }}
                  issue-number: ${{ steps['last-issue']['outputs']['issue-number'] }}
                  labels: |
                      ${{ env.issue-lookup-label }}
                      broken-link, docs
