name: Check links

on:
    pull_request:
        branches: [main]
    workflow_dispatch:
    schedule:
        - cron: '16 2 * * 6'

jobs:
    validate:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
        env:
            issue-lookup-label: automated-link-issue
            issue-content: ./lychee-out.md
        steps:
            - uses: actions/checkout@v4

            - name: Restore lychee cache
              uses: actions/cache@v4
              with:
                  path: .lycheecache
                  key: cache-lychee-${{ github.sha }}
                  restore-keys: cache-lychee-

            - name: Extract URLs from JSON files
              run: |
                  mkdir -p extracted-urls
                  jq -r '.. | objects | .url? // empty' ./conferences/2024/*.json ./conferences/2025/*.json ./conferences/2026/*.json > extracted-urls/urls.txt

            - name: Check URLs with lychee
              run: |
                  # Read URLs from file and check each URL
                  while IFS= read -r url; do
                    echo "Checking $url"
                    lychee "$url" --verbose --no-progress || exit 1
                  done < extracted-urls/urls.txt

            - name: Generate report
              run: |
                  # Generate report if needed (custom script or use output from lychee)
                  echo "Generate your report here"
                  # For example, you can redirect output to a file
                  lychee --verbose --no-progress extracted-urls/urls.txt > ${{ env.issue-content }}

            - name: Create or Update GitHub Issue
              if: ${{ failure() }}
              uses: peter-evans/create-issue-from-file@v4
              with:
                  title: 'docs: Broken links found'
                  content-filepath: ${{ env.issue-content }}
                  issue-number: ${{ steps['last-issue']['outputs']['issue-number'] }}
                  labels: |
                      ${{ env.issue-lookup-label }}
                      broken-link, docs
